"use client"

import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

// Define template types and their form elements
export const FORM_TEMPLATES = {
  CONTACT: "contact",
  SURVEY: "survey",
  EVENT: "event",
  JOB: "job",
  FEEDBACK: "feedback",
  ORDER: "order",
  NEWSLETTER: "newsletter",
  RSVP: "rsvp",
  APPOINTMENT: "appointment",
  QUIZ: "quiz",
}

// Template definitions with preview images and form elements
export const templates = [
  {
    id: FORM_TEMPLATES.CONTACT,
    name: "Contact Form",
    description: "A clean, modern contact form with name, email, and message fields.",
    image: "/placeholder.svg?height=400&width=300&text=Contact+Form",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        validationMessage: "Please enter a valid email address",
        width: "full",
      },
      {
        type: "text",
        id: "subject",
        label: "Subject",
        placeholder: "What is this regarding?",
        width: "full",
      },
      {
        type: "textarea",
        id: "message",
        label: "Message",
        placeholder: "Type your message here...",
        required: true,
        minLength: 10,
        validationMessage: "Please enter a message with at least 10 characters",
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.SURVEY,
    name: "Customer Survey",
    description: "Collect detailed feedback with this modern survey template.",
    image: "/placeholder.svg?height=400&width=300&text=Survey+Form",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Your Name",
        placeholder: "Enter your name",
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        width: "full",
      },
      {
        type: "select",
        id: "product",
        label: "Which product are you providing feedback for?",
        placeholder: "Select a product",
        required: true,
        options: ["Product A", "Product B", "Product C", "Product D"],
        width: "full",
      },
      {
        type: "rating",
        id: "satisfaction",
        label: "How satisfied are you with our product?",
        maxRating: 5,
        required: true,
        width: "full",
      },
      {
        type: "radio",
        id: "recommend",
        label: "Would you recommend our product to others?",
        options: ["Definitely", "Maybe", "Not sure", "No"],
        required: true,
        width: "full",
      },
      {
        type: "checkbox",
        id: "features",
        label: "Which features do you value most?",
        options: ["Ease of use", "Performance", "Design", "Customer support", "Price"],
        width: "full",
      },
      {
        type: "textarea",
        id: "improvements",
        label: "How could we improve our product?",
        placeholder: "Share your suggestions...",
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.EVENT,
    name: "Event Registration",
    description: "A sleek form for event registrations with all necessary fields.",
    image: "/placeholder.svg?height=400&width=300&text=Event+Registration",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        width: "full",
      },
      {
        type: "phone",
        id: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        width: "full",
      },
      {
        type: "select",
        id: "ticket",
        label: "Ticket Type",
        placeholder: "Select ticket type",
        required: true,
        options: ["General Admission", "VIP", "Early Bird", "Group (5+)"],
        width: "full",
      },
      {
        type: "number",
        id: "quantity",
        label: "Number of Tickets",
        placeholder: "1",
        min: 1,
        max: 10,
        required: true,
        width: "medium",
      },
      {
        type: "checkbox",
        id: "extras",
        label: "Additional Options",
        options: ["Parking pass", "Meal voucher", "Merchandise package", "After-party access"],
        width: "full",
      },
      {
        type: "textarea",
        id: "specialRequests",
        label: "Special Requests",
        placeholder: "Any dietary restrictions or accessibility needs?",
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.JOB,
    name: "Job Application",
    description: "Professional job application form with resume upload.",
    image: "/placeholder.svg?height=400&width=300&text=Job+Application",
    elements: [
      {
        type: "text",
        id: "firstName",
        label: "First Name",
        placeholder: "Enter your first name",
        required: true,
        width: "medium",
      },
      {
        type: "text",
        id: "lastName",
        label: "Last Name",
        placeholder: "Enter your last name",
        required: true,
        width: "medium",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        width: "full",
      },
      {
        type: "phone",
        id: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        width: "full",
      },
      {
        type: "select",
        id: "position",
        label: "Position Applied For",
        placeholder: "Select a position",
        required: true,
        options: [
          "Software Engineer",
          "Product Manager",
          "UX Designer",
          "Marketing Specialist",
          "Sales Representative",
        ],
        width: "full",
      },
      {
        type: "file",
        id: "resume",
        label: "Resume/CV",
        required: true,
        description: "Upload your resume (PDF, DOC, or DOCX)",
        width: "full",
      },
      {
        type: "file",
        id: "coverLetter",
        label: "Cover Letter",
        description: "Upload your cover letter (optional)",
        width: "full",
      },
      {
        type: "textarea",
        id: "experience",
        label: "Relevant Experience",
        placeholder: "Briefly describe your relevant experience...",
        required: true,
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.FEEDBACK,
    name: "Product Feedback",
    description: "Collect detailed product feedback with this modern form.",
    image: "/placeholder.svg?height=400&width=300&text=Product+Feedback",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Your Name",
        placeholder: "Enter your name",
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        width: "full",
      },
      {
        type: "select",
        id: "product",
        label: "Product",
        placeholder: "Select a product",
        required: true,
        options: ["Product A", "Product B", "Product C"],
        width: "full",
      },
      {
        type: "rating",
        id: "rating",
        label: "How would you rate this product?",
        maxRating: 5,
        required: true,
        width: "full",
      },
      {
        type: "checkbox",
        id: "likedFeatures",
        label: "What did you like about this product?",
        options: ["Quality", "Price", "Design", "Functionality", "Customer Service"],
        width: "full",
      },
      {
        type: "textarea",
        id: "improvements",
        label: "How could we improve this product?",
        placeholder: "Share your suggestions...",
        width: "full",
      },
      {
        type: "radio",
        id: "recommend",
        label: "Would you recommend this product to others?",
        options: ["Yes, definitely", "Maybe", "No"],
        required: true,
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.ORDER,
    name: "Order Form",
    description: "A comprehensive order form with product selection and shipping details.",
    image: "/placeholder.svg?height=400&width=300&text=Order+Form",
    elements: [
      {
        type: "text",
        id: "firstName",
        label: "First Name",
        placeholder: "Enter your first name",
        required: true,
        width: "medium",
      },
      {
        type: "text",
        id: "lastName",
        label: "Last Name",
        placeholder: "Enter your last name",
        required: true,
        width: "medium",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        width: "full",
      },
      {
        type: "phone",
        id: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        width: "full",
      },
      {
        type: "text",
        id: "address",
        label: "Shipping Address",
        placeholder: "Enter your street address",
        required: true,
        width: "full",
      },
      {
        type: "text",
        id: "city",
        label: "City",
        placeholder: "Enter your city",
        required: true,
        width: "medium",
      },
      {
        type: "text",
        id: "zipCode",
        label: "ZIP / Postal Code",
        placeholder: "Enter your ZIP code",
        required: true,
        width: "small",
      },
      {
        type: "select",
        id: "country",
        label: "Country",
        placeholder: "Select your country",
        required: true,
        options: ["United States", "Canada", "United Kingdom", "Australia", "Germany", "France", "Japan"],
        width: "medium",
      },
      {
        type: "select",
        id: "product",
        label: "Product",
        placeholder: "Select a product",
        required: true,
        options: ["Product A - $19.99", "Product B - $29.99", "Product C - $39.99", "Product D - $49.99"],
        width: "full",
      },
      {
        type: "number",
        id: "quantity",
        label: "Quantity",
        placeholder: "1",
        min: 1,
        max: 100,
        required: true,
        width: "small",
      },
      {
        type: "textarea",
        id: "notes",
        label: "Order Notes",
        placeholder: "Any special instructions for your order?",
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.NEWSLETTER,
    name: "Newsletter Subscription",
    description: "A simple, elegant newsletter subscription form.",
    image: "/placeholder.svg?height=400&width=300&text=Newsletter",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Your Name",
        placeholder: "Enter your name",
        required: true,
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        validationMessage: "Please enter a valid email address",
        width: "full",
      },
      {
        type: "checkbox",
        id: "interests",
        label: "I'm interested in receiving updates about:",
        options: ["New products", "Special offers", "Company news", "Industry insights"],
        width: "full",
      },
      {
        type: "select",
        id: "frequency",
        label: "Email Frequency",
        placeholder: "Select frequency",
        options: ["Daily", "Weekly", "Monthly", "Quarterly"],
        width: "medium",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.RSVP,
    name: "RSVP Form",
    description: "A stylish RSVP form for events and gatherings.",
    image: "/placeholder.svg?height=400&width=300&text=RSVP+Form",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        width: "full",
      },
      {
        type: "phone",
        id: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        width: "full",
      },
      {
        type: "radio",
        id: "attendance",
        label: "Will you be attending?",
        options: ["Yes, I will attend", "No, I cannot attend"],
        required: true,
        width: "full",
      },
      {
        type: "number",
        id: "guests",
        label: "Number of Guests (including yourself)",
        placeholder: "1",
        min: 1,
        max: 10,
        required: true,
        width: "small",
      },
      {
        type: "textarea",
        id: "dietaryRestrictions",
        label: "Dietary Restrictions",
        placeholder: "Please list any dietary restrictions or allergies...",
        width: "full",
      },
      {
        type: "textarea",
        id: "message",
        label: "Message to the Host",
        placeholder: "Optional message...",
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.APPOINTMENT,
    name: "Appointment Booking",
    description: "A professional appointment booking form with date and time selection.",
    image: "/placeholder.svg?height=400&width=300&text=Appointment+Booking",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Full Name",
        placeholder: "Enter your full name",
        required: true,
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        width: "full",
      },
      {
        type: "phone",
        id: "phone",
        label: "Phone Number",
        placeholder: "Enter your phone number",
        required: true,
        width: "full",
      },
      {
        type: "select",
        id: "service",
        label: "Service Type",
        placeholder: "Select a service",
        required: true,
        options: ["Consultation", "Follow-up", "New Client Meeting", "Service A", "Service B"],
        width: "full",
      },
      {
        type: "date",
        id: "date",
        label: "Preferred Date",
        required: true,
        width: "medium",
      },
      {
        type: "select",
        id: "time",
        label: "Preferred Time",
        placeholder: "Select a time",
        required: true,
        options: ["9:00 AM", "10:00 AM", "11:00 AM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM"],
        width: "medium",
      },
      {
        type: "textarea",
        id: "notes",
        label: "Additional Notes",
        placeholder: "Any specific requirements or questions?",
        width: "full",
      },
    ],
  },
  {
    id: FORM_TEMPLATES.QUIZ,
    name: "Quiz Form",
    description: "An interactive quiz form with various question types.",
    image: "/placeholder.svg?height=400&width=300&text=Quiz+Form",
    elements: [
      {
        type: "text",
        id: "name",
        label: "Your Name",
        placeholder: "Enter your name",
        required: true,
        width: "full",
      },
      {
        type: "email",
        id: "email",
        label: "Email Address",
        placeholder: "your.email@example.com",
        required: true,
        width: "full",
      },
      {
        type: "radio",
        id: "question1",
        label: "Question 1: What is the capital of France?",
        options: ["Paris", "London", "Berlin", "Madrid"],
        required: true,
        width: "full",
      },
      {
        type: "checkbox",
        id: "question2",
        label: "Question 2: Which of the following are programming languages?",
        options: ["JavaScript", "HTML", "Python", "Photoshop", "Java"],
        required: true,
        width: "full",
      },
      {
        type: "select",
        id: "question3",
        label: "Question 3: Which planet is closest to the sun?",
        placeholder: "Select your answer",
        options: ["Mercury", "Venus", "Earth", "Mars"],
        required: true,
        width: "full",
      },
      {
        type: "textarea",
        id: "question4",
        label: "Question 4: Briefly explain the concept of climate change.",
        placeholder: "Your answer...",
        required: true,
        minLength: 50,
        width: "full",
      },
      {
        type: "rating",
        id: "question5",
        label: "Question 5: How would you rate your knowledge on this subject?",
        maxRating: 5,
        required: true,
        width: "full",
      },
    ],
  },
]

export function TemplateGallery({ onSelectTemplate }) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4">
      {templates.map((template) => (
        <Card key={template.id} className="overflow-hidden hover:shadow-md transition-shadow">
          <CardContent className="p-0">
            <div className="relative h-40 bg-muted">
              <img src={template.image || "/placeholder.svg"} alt={template.name} fill className="object-cover" />
            </div>
            <div className="p-4">
              <h3 className="font-semibold text-lg">{template.name}</h3>
              <p className="text-sm text-muted-foreground mt-1">{template.description}</p>
            </div>
          </CardContent>
          <CardFooter className="p-4 pt-0">
            <Button variant="default" className="w-full" onClick={() => onSelectTemplate(template)}>
              Use Template
            </Button>
          </CardFooter>
        </Card>
      ))}
    </div>
  )
}

